two_theta: [10.0, 50.0]
step_size: 0.015
wavelength: 1.20789
transmission: true # if XRD transmission mode
strain: 0.01 # lattice strain for varied structure
texture: 0.7 # maximum texture of powder

sample_holder: 15.0 # sample holder angle (in degrees)
background_type: "chebyshev" # chebyshev or decay

fwhm_range: [0.3, 0.9] # peak fwhm in radians [min, max]
noise_level: [0.03, 0.07] # SNR (level noise to max peak) in [min, max]
multiphase_peak_num: 2 # number of multi-phase peaks per scan
multiphase_peak_range: [17.0, 45.0] # alternative [25.0, 35.0]
multiphase_peak_height: [0.05, 0.1] # [min, max] of multiphase peaks
multiphase_restricted: 25 # no multi-phase peaks in [-25, 25] range around peaks

random_shift: 20 # random linear shift applied to simulated signals
seed: null